# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Hanky
google_analytics: dbyll
title: Hanky

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Hanky

description: Stylish Jekyll Theme
author:
  name: Brian Song
  email: bhsong@ucsc.edu
  github: hankyana
  twitter: itshankyul
  pinterest: null
  linkedin: brian-song-8010b5184
  bio: Cognitive Science, focus on HCI/AI. Class of 2022. Working on Data Analytics.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: null
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://imgur.com/a/af5xTd8

BASE_PATH:

plugins:
  - jekyll-paginate
